name = "TerrariaWiringHelper"
uuid = "25498505-48c7-4d30-801f-92d3f675baa4"
authors = ["Tianyi Pu <912396513@qq.com> and contributors"]
version = "1.0.0-DEV"

[compat]
Documenter = "1"
Test = "1"
julia = "1.12"

[extras]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "Documenter"]

[workspace]
projects = ["docs"]
