name = "TerrariaWiringHelper"
uuid = "25498505-48c7-4d30-801f-92d3f675baa4"
version = "0.0.2"
authors = ["Tianyi Pu <912396513@qq.com> and contributors"]

[workspace]
projects = ["docs"]

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"

[compat]
Documenter = "1"
LinearAlgebra = "1"
StaticArrays = "1"
Test = "1"
julia = "1.12"

[extras]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "Documenter"]
